import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';

const Home: NextPage = () => {
  return (
    <div className="bg-primary min-w-[1200px]">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-neutral-50 text-primary flex items-center justify-center">
        <div className="w-full p-14 max-w-6xl flex">
          <div className="flex-1">
            <h1 className="text-4xl font-bold my-2">
              복잡한 부동산 세금,
              <br />
              여P가 쉽게 가이드 합니다.
            </h1>
            <br />
            <p>
              98%의 세무사들조차 잦은 부동산 세법 개정으로 일 못하겠다고
              토로합니다.
              <br />
              부동산 세금 제도가 난수표처럼 어렵다고 불평합니다.
              <br />
              그리고 생각지도 못했던 곳에서 증여세 등이 과세되곤 합니다.
              <br />
              세금은 갑자기 너무 중요해졌는데 너무 어렵고 계속 바뀝니다.
              <br />
              하지만 걱정 마세요, 여P가 여러분 각자의 상황에 맞게 가이드
              해드립니다.
            </p>
          </div>
          <div className="flex-1"></div>
        </div>
      </main>
      <section className="bg-primary text-white flex flex-col items-center justify-center">
        <h2 className="w-full pt-10 px-14 max-w-6xl text-lg font-system_semibold">
          어렵지 않은 세금 가이드
        </h2>
        <div className="font-system w-full pt-5 pb-14 px-14 max-w-6xl flex justify-between gap-x-4">
          <div
            className="rounded-3xl w-52 h-80 px-10 py-6 bg-white text-primary"
            style={{ position: 'relative' }}
          >
            <b>
              지금 그대로
              <br />
              유지한다면
              <br />내 세금은?
            </b>
            <ul>
              <li>종부세</li>
              <li>재산세</li>
            </ul>
            <div style={{ position: 'absolute', bottom: 30, right: 20 }}>
              <Image
                src="/s1c.png"
                width="100"
                height="100"
                alt="보유세"
              ></Image>
            </div>
          </div>
          <div
            className="rounded-3xl w-52 h-80 px-10 py-6 bg-white text-primary"
            style={{ position: 'relative' }}
          >
            <b>
              집을 더 사면
              <br />
              세금은
              <br />
              얼마일까?
            </b>
            <ul>
              <li>취득세</li>
              <li>취득 후 보유세</li>
            </ul>
            <div style={{ position: 'absolute', bottom: 30, right: 20 }}>
              <Image
                src="/s2c.png"
                width="100"
                height="100"
                alt="취득세"
              ></Image>
            </div>
          </div>
          <div
            className="rounded-3xl w-52 h-80 px-10 py-6 bg-white text-primary"
            style={{ position: 'relative' }}
          >
            <b>
              집을 팔면
              <br />
              세금은
              <br />
              얼마일까?
            </b>
            <ul>
              <li>양도소득세</li>
            </ul>
            <div style={{ position: 'absolute', bottom: 30, right: 20 }}>
              <Image
                src="/s3c.png"
                width="100"
                height="100"
                alt="양도소득세"
              ></Image>
            </div>
          </div>
          <div
            className="rounded-3xl w-52 h-80 px-10 py-6 bg-white text-primary"
            style={{ position: 'relative' }}
          >
            <b>
              내 집을
              <br />
              임대하면
              <br />
              세금은?
            </b>
            <ul>
              <li>전세/월세의</li>
              <li>세후 수익률</li>
            </ul>
            <div style={{ position: 'absolute', bottom: 30, right: 20 }}>
              <Image
                src="/s4c.png"
                width="100"
                height="100"
                alt="세후수익률"
              ></Image>
            </div>
          </div>
        </div>
      </section>
      <section className="font-system bg-black text-white flex flex-col items-center justify-center">
        <div className="w-full pt-10 px-14 max-w-6xl text-sm">
          고객센터 / 서비스 문의:{' '}
          <a href="mailto:contact@hsj.company">contact@hsj.company</a>
        </div>
        <div className="w-full pt-2 px-14 max-w-6xl text-sm">
          <a href="https://www.yourpb.biz/terms.html">이용약관</a>
          <span className="mx-1">&middot;</span>
          <a href="https://www.yourpb.biz/privacy.html">개인정보처리방침</a>
          <span className="mx-1">&middot;</span>
          <a href="#!">FAQ</a>
        </div>
        <div className="w-full pt-2 px-14 max-w-6xl text-sm">
          (주)에이치에스제이앤컴퍼니 대표 한상직 | 사업자등록번호 686-88-02358
        </div>
        <div className="w-full px-14 max-w-6xl text-sm">
          사업장 소재지 부산광역시 강서구 미음산단5로41번길 71 201호 (미음동,
          부산글로벌테크비즈센터)
        </div>
        <div className="w-full pt-2 pb-10 px-14 max-w-6xl text-sm">
          &copy; 2021 HSJ&Company Corp. All Rights Reserved.
        </div>
      </section>
    </div>
  );
};

export default Home;
